# Site settings
name: Eat Your History
description: 'Flash cooked crunchy bits of bite-size history'

baseurl: '/eat-your-historyg' # the subpath of your site, e.g. /blog
url: 'http://jeenalee.github.io' # the base hostname & protocol for your site

# Build settings
markdown:            kramdown
relative_permalinks: false
permalink:           :title/

pagination:          true
paginate:            8
paginate_path:       page/:num/

author:
    name: 'Jeena Lee'
    email: ''
    uri: 'https://github.com/jeenalee'

sass:
    sass_dir: _sass
    style:    compressed

defaults:
  -
      scope:
        path: '_posts'
        type: 'posts'
      values:
        reading_time: false
        # Meta
        show_tags: false
        show_categories: false
        # Social
        share_buttons: true
        disqus: false

gems:
    - jekyll-feed
    - jekyll-sitemap
    - jekyll-paginate
